name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      - mvp-4.5  # add/remove branches as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2  # If using pnpm; remove if using npm or yarn
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g wrangler
      - run: npm install
        working-directory: ./api  # or your Worker directory
      - run: wrangler deploy
        working-directory: ./api  # or your Worker directory
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
