name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      - mvp-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm install --save-dev @cloudflare/workers-types

      - run: npm run build

      - run: npm run build:worker

      # NEW: Explicitly show file output so we can verify dist/worker content
      - name: Show build output structure
        run: |
          echo "::group::dist/worker contents"
          ls -R dist/worker
          echo "::endgroup::"

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy dist/worker/src/index.js
